# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    networks:
      - appNetwork
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@test.com
      - PGADMIN_DEFAULT_PASSWORD=pass
    depends_on:
      - db
    networks:
      - appNetwork
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
    db-data:
    pgadmin:

networks:
  appNetwork:
    driver: bridge